local thermalMat = Material("pp/texturize/plain.png")

-- also:
-- NoFade
-- EquipSound
-- UnequipSound
-- EquipDelay
-- UnequipDelay
ArcticNVGs = {
    {
        ShortName = "nvg_gpnvg",
        VManipIn = "nvg_gpnvg_in",
        VManipOut = "nvg_gpnvg_out",
        Model = "models/arctic_nvgs/nvg_gpnvg.mdl",
        FullColor = false,
        EquipDelay = 1.325,
        ColorCorrectSettings = {
            ["$pp_colour_addr"] = 0,
            ["$pp_colour_addg"] = 0.02,
            ["$pp_colour_addb"] = 0.02,
            ["$pp_colour_brightness"] = 0.01,
            ["$pp_colour_contrast"] = 4.5,
            ["$pp_colour_colour"] = 1,
            ["$pp_colour_mulr"] = 0,
            ["$pp_colour_mulg"] = 0,
            ["$pp_colour_mulb"] = 0,
        },
        EquipSound = "arctic_nvgs/nvg_on_1.wav",
        UnequipSound = "arctic_nvgs/nvg_off_1.wav",
        BloomSettings = {
            darken = 0,
            multiply = 1,
            sizex = 4,
            sizey = 4,
            passes = 1,
            colormultiply = 1,
            red = 1,
            green = 1,
            blue = 1,
        },
        ToyTownSettings = {
            ["passes"] = 20,
            ["height"] = 0.7,
        },
        ActiveLight = false,
        EffectFunction = nil,
        Overlay = Material("arctic_nvg/faint.png", "mips"),
        -- ScaleToSquare = false,
        Entity = "arctic_nvg_gpnvg",
        Offset = Vector(0, 0, 0),
        OffsetAngle = Angle(0, 0, 0)
    },
    {
        ShortName = "nvg_gpnvg_g",
        VManipIn = "nvg_gpnvg_in",
        VManipOut = "nvg_gpnvg_out",
        Model = "models/arctic_nvgs/nvg_gpnvg.mdl",
        FullColor = false,
        EquipDelay = 1.325,
        ColorCorrectSettings = {
            ["$pp_colour_addr"] = 0,
            ["$pp_colour_addg"] = 0.025,
            ["$pp_colour_addb"] = -0.05,
            ["$pp_colour_brightness"] = 0.01,
            ["$pp_colour_contrast"] = 4.5,
            ["$pp_colour_colour"] = 1,
            ["$pp_colour_mulr"] = 0,
            ["$pp_colour_mulg"] = 0,
            ["$pp_colour_mulb"] = 0,
        },
        EquipSound = "arctic_nvgs/nvg_on_1.wav",
        UnequipSound = "arctic_nvgs/nvg_off_1.wav",
        BloomSettings = {
            darken = 0,
            multiply = 1,
            sizex = 4,
            sizey = 4,
            passes = 1,
            colormultiply = 1,
            red = 1,
            green = 1,
            blue = 1,
        },
        ToyTownSettings = {
            ["passes"] = 20,
            ["height"] = 0.7,
        },
    
        ActiveLight = false,
        EffectFunction = nil,
        Overlay = Material("arctic_nvg/faint.png", "mips"),
        -- ScaleToSquare = false,
        Entity = "arctic_nvg_gpnvg_green",
        Offset = Vector(0, 0, 0),
        OffsetAngle = Angle(0, 0, 0)
    },
    {
        ShortName = "nvg_gpnvg_a",
        VManipIn = "nvg_gpnvg_in",
        VManipOut = "nvg_gpnvg_out",
        Model = "models/arctic_nvgs/nvg_gpnvg.mdl",
        FullColor = false,
        EquipDelay = 1.325,
        ColorCorrectSettings = {
            ["$pp_colour_addr"] = 0.03,
            ["$pp_colour_addg"] = 0.01,
            ["$pp_colour_addb"] = -0.1,
            ["$pp_colour_brightness"] = 0.01,
            ["$pp_colour_contrast"] = 4.5,
            ["$pp_colour_colour"] = 1,
            ["$pp_colour_mulr"] = 0,
            ["$pp_colour_mulg"] = 0,
            ["$pp_colour_mulb"] = 0,
        },
        EquipSound = "arctic_nvgs/nvg_on_1.wav",
        UnequipSound = "arctic_nvgs/nvg_off_1.wav",
        BloomSettings = {
            darken = 0,
            multiply = 1,
            sizex = 4,
            sizey = 4,
            passes = 1,
            colormultiply = 1,
            red = 1,
            green = 1,
            blue = 1,
        },
        ToyTownSettings = {
            ["passes"] = 20,
            ["height"] = 0.7,
        },
        ActiveLight = false,
        EffectFunction = nil,
        Overlay = Material("arctic_nvg/faint.png", "mips"),
        -- ScaleToSquare = false,
        Entity = "arctic_nvg_gpnvg_amber",
        Offset = Vector(0, 0, 0),
        OffsetAngle = Angle(0, 0, 0)
    },
    {
        ShortName = "nvg_gpnvg_r",
        VManipIn = "nvg_gpnvg_in",
        VManipOut = "nvg_gpnvg_out",
        Model = "models/arctic_nvgs/nvg_gpnvg.mdl",
        FullColor = false,
        EquipDelay = 1.325,
        ColorCorrectSettings = {
            ["$pp_colour_addr"] = 0.05,
            ["$pp_colour_addg"] = -0.05,
            ["$pp_colour_addb"] = -0.05,
            ["$pp_colour_brightness"] = 0.01,
            ["$pp_colour_contrast"] = 4.5,
            ["$pp_colour_colour"] = 1,
            ["$pp_colour_mulr"] = 0,
            ["$pp_colour_mulg"] = 0,
            ["$pp_colour_mulb"] = 0,
        },
        EquipSound = "arctic_nvgs/nvg_on_1.wav",
        UnequipSound = "arctic_nvgs/nvg_off_1.wav",
        BloomSettings = {
            darken = 0,
            multiply = 1,
            sizex = 4,
            sizey = 4,
            passes = 1,
            colormultiply = 1,
            red = 1,
            green = 1,
            blue = 1,
        },
        ToyTownSettings = {
            ["passes"] = 20,
            ["height"] = 0.7,
        },
        ActiveLight = false,
        EffectFunction = nil,
        Overlay = Material("arctic_nvg/faint.png", "mips"),
        -- ScaleToSquare = false,
        Entity = "arctic_nvg_gpnvg_red",
        Offset = Vector(0, 0, 0),
        OffsetAngle = Angle(0, 0, 0)
    },
    {
        ShortName = "nvg_gpnvg_b",
        VManipIn = "nvg_gpnvg_in",
        VManipOut = "nvg_gpnvg_out",
        Model = "models/arctic_nvgs/nvg_gpnvg.mdl",
        FullColor = false,
        EquipDelay = 1.325,
        ColorCorrectSettings = {
            ["$pp_colour_addr"] = -0.03,
            ["$pp_colour_addg"] = -0.03,
            ["$pp_colour_addb"] = 0.03,
            ["$pp_colour_brightness"] = 0.01,
            ["$pp_colour_contrast"] = 4.5,
            ["$pp_colour_colour"] = 1,
            ["$pp_colour_mulr"] = 0,
            ["$pp_colour_mulg"] = 0,
            ["$pp_colour_mulb"] = 0,
        },
        EquipSound = "arctic_nvgs/nvg_on_1.wav",
        UnequipSound = "arctic_nvgs/nvg_off_1.wav",
        BloomSettings = {
            darken = 0,
            multiply = 1,
            sizex = 4,
            sizey = 4,
            passes = 1,
            colormultiply = 1,
            red = 1,
            green = 1,
            blue = 1,
        },
        ToyTownSettings = {
            ["passes"] = 20,
            ["height"] = 0.7,
        },
        ActiveLight = false,
        EffectFunction = nil,
        Overlay = Material("arctic_nvg/faint.png", "mips"),
        -- ScaleToSquare = false,
        Entity = "arctic_nvg_gpnvg_blue",
        Offset = Vector(0, 0, 0),
        OffsetAngle = Angle(0, 0, 0)
    },
    {
        ShortName = "nvg_gpnvg_p",
        VManipIn = "nvg_gpnvg_in",
        VManipOut = "nvg_gpnvg_out",
        Model = "models/arctic_nvgs/nvg_gpnvg.mdl",
        FullColor = false,
        EquipDelay = 1.325,
        ColorCorrectSettings = {
            ["$pp_colour_addr"] = -0.01,
            ["$pp_colour_addg"] = -0.05,
            ["$pp_colour_addb"] = 0.02,
            ["$pp_colour_brightness"] = 0.01,
            ["$pp_colour_contrast"] = 4.5,
            ["$pp_colour_colour"] = 1,
            ["$pp_colour_mulr"] = 0,
            ["$pp_colour_mulg"] = 0,
            ["$pp_colour_mulb"] = 0,
        },
        EquipSound = "arctic_nvgs/nvg_on_1.wav",
        UnequipSound = "arctic_nvgs/nvg_off_1.wav",
        BloomSettings = {
            darken = 0,
            multiply = 1,
            sizex = 4,
            sizey = 4,
            passes = 1,
            colormultiply = 1,
            red = 1,
            green = 1,
            blue = 1,
        },
        ToyTownSettings = {
            ["passes"] = 20,
            ["height"] = 0.7,
        },
        ActiveLight = false,
        EffectFunction = nil,
        Overlay = Material("arctic_nvg/faint.png", "mips"),
        -- ScaleToSquare = false,
        Entity = "arctic_nvg_gpnvg_purple",
        Offset = Vector(0, 0, 0),
        OffsetAngle = Angle(0, 0, 0)
    },
    {
        ShortName = "nvg_gpnvg_c",
        VManipIn = "nvg_gpnvg_in",
        VManipOut = "nvg_gpnvg_out",
        Model = "models/arctic_nvgs/nvg_gpnvg.mdl",
        FullColor = false,
        EquipDelay = 1.325,
        ColorCorrectSettings = {
            ["$pp_colour_addr"] = -0.05,
            ["$pp_colour_addg"] = 0,
            ["$pp_colour_addb"] = 0,
            ["$pp_colour_brightness"] = 0.01,
            ["$pp_colour_contrast"] = 4.5,
            ["$pp_colour_colour"] = 1,
            ["$pp_colour_mulr"] = 0,
            ["$pp_colour_mulg"] = 0,
            ["$pp_colour_mulb"] = 0,
        },
        EquipSound = "arctic_nvgs/nvg_on_1.wav",
        UnequipSound = "arctic_nvgs/nvg_off_1.wav",
        BloomSettings = {
            darken = 0,
            multiply = 1,
            sizex = 4,
            sizey = 4,
            passes = 1,
            colormultiply = 1,
            red = 1,
            green = 1,
            blue = 1,
        },
        ToyTownSettings = {
            ["passes"] = 20,
            ["height"] = 0.7,
        },
        ActiveLight = false,
        EffectFunction = nil,
        Overlay = Material("arctic_nvg/faint.png", "mips"),
        -- ScaleToSquare = false,
        Entity = "arctic_nvg_gpnvg_cyan",
        Offset = Vector(0, 0, 0),
        OffsetAngle = Angle(0, 0, 0)
    },
    {
        ShortName = "nvg_gpnvg_ru",
        VManipIn = "nvg_gpnvg_in",
        VManipOut = "nvg_gpnvg_out",
        Model = "models/arctic_nvgs/nvg_gpnvg.mdl",
        FullColor = false,
        EquipDelay = 1.325,
        ColorCorrectSettings = {
            ["$pp_colour_addr"] = -0.05,
            ["$pp_colour_addg"] = 0.01,
            ["$pp_colour_addb"] = -0.1,
            ["$pp_colour_brightness"] = 0.01,
            ["$pp_colour_contrast"] = 4.5,
            ["$pp_colour_colour"] = 1,
            ["$pp_colour_mulr"] = 0,
            ["$pp_colour_mulg"] = 0,
            ["$pp_colour_mulb"] = 0,
        },
        EquipSound = "arctic_nvgs/nvg_on_1.wav",
        UnequipSound = "arctic_nvgs/nvg_off_1.wav",
        BloomSettings = {
            darken = 0,
            multiply = 1,
            sizex = 4,
            sizey = 4,
            passes = 1,
            colormultiply = 1,
            red = 1,
            green = 1,
            blue = 1,
        },
        ToyTownSettings = {
            ["passes"] = 20,
            ["height"] = 0.7,
        },
        ActiveLight = false,
        EffectFunction = nil,
        Overlay = Material("arctic_nvg/faint.png", "mips"),
        -- ScaleToSquare = false,
        Entity = "arctic_nvg_gpnvg_russian",
        Offset = Vector(0, 0, 0),
        OffsetAngle = Angle(0, 0, 0)
    },
    {
        ShortName = "nvg_gpnvg_t",
        VManipIn = "nvg_gpnvg_in",
        VManipOut = "nvg_gpnvg_out",
        Model = "models/arctic_nvgs/nvg_gpnvg.mdl",
        FullColor = false,
        EquipDelay = 1.325,
        ColorCorrectSettings = {
            ["$pp_colour_addr"] = -0.04,
            ["$pp_colour_addg"] = 0.02,
            ["$pp_colour_addb"] = 0.01,
            ["$pp_colour_brightness"] = 0.01,
            ["$pp_colour_contrast"] = 4.5,
            ["$pp_colour_colour"] = 1,
            ["$pp_colour_mulr"] = 0,
            ["$pp_colour_mulg"] = 0,
            ["$pp_colour_mulb"] = 0,
        },
        EquipSound = "arctic_nvgs/nvg_on_1.wav",
        UnequipSound = "arctic_nvgs/nvg_off_1.wav",
        BloomSettings = {
            darken = 0,
            multiply = 1,
            sizex = 4,
            sizey = 4,
            passes = 1,
            colormultiply = 1,
            red = 1,
            green = 1,
            blue = 1,
        },
        ToyTownSettings = {
            ["passes"] = 20,
            ["height"] = 0.7,
        },
        ActiveLight = false,
        EffectFunction = nil,
        Overlay = Material("arctic_nvg/faint.png", "mips"),
        -- ScaleToSquare = false,
        Entity = "arctic_nvg_gpnvg_teal",
        Offset = Vector(0, 0, 0),
        OffsetAngle = Angle(0, 0, 0)
    },
    {
        ShortName = "nvg_gpnvg_hp",
        VManipIn = "nvg_gpnvg_in",
        VManipOut = "nvg_gpnvg_out",
        Model = "models/arctic_nvgs/nvg_gpnvg.mdl",
        FullColor = false,
        EquipDelay = 1.325,
        ColorCorrectSettings = {
            ["$pp_colour_addr"] = 0.04,
            ["$pp_colour_addg"] = -0.05,
            ["$pp_colour_addb"] = 0.005,
            ["$pp_colour_brightness"] = 0.01,
            ["$pp_colour_contrast"] = 4.5,
            ["$pp_colour_colour"] = 1,
            ["$pp_colour_mulr"] = 0,
            ["$pp_colour_mulg"] = 0,
            ["$pp_colour_mulb"] = 0,
        },
        EquipSound = "arctic_nvgs/nvg_on_1.wav",
        UnequipSound = "arctic_nvgs/nvg_off_1.wav",
        BloomSettings = {
            darken = 0,
            multiply = 1,
            sizex = 4,
            sizey = 4,
            passes = 1,
            colormultiply = 1,
            red = 1,
            green = 1,
            blue = 1,
        },
        ToyTownSettings = {
            ["passes"] = 20,
            ["height"] = 0.7,
        },
        ActiveLight = false,
        EffectFunction = nil,
        Overlay = Material("arctic_nvg/faint.png", "mips"),
        -- ScaleToSquare = false,
        Entity = "arctic_nvg_gpnvg_hotpink",
        Offset = Vector(0, 0, 0),
        OffsetAngle = Angle(0, 0, 0)
    },
    {
        ShortName = "nvg_gpnvg_bw",
        VManipIn = "nvg_gpnvg_in",
        VManipOut = "nvg_gpnvg_out",
        Model = "models/arctic_nvgs/nvg_gpnvg.mdl",
        FullColor = false,
        EquipDelay = 1.325,
        ColorCorrectSettings = {
            ["$pp_colour_addr"] = 0,
            ["$pp_colour_addg"] = 0,
            ["$pp_colour_addb"] = 0,
            ["$pp_colour_brightness"] = 0.01,
            ["$pp_colour_contrast"] = 4.5,
            ["$pp_colour_colour"] = 1,
            ["$pp_colour_mulr"] = 0,
            ["$pp_colour_mulg"] = 0,
            ["$pp_colour_mulb"] = 0,
        },
        EquipSound = "arctic_nvgs/nvg_on_1.wav",
        UnequipSound = "arctic_nvgs/nvg_off_1.wav",
        BloomSettings = {
            darken = 0,
            multiply = 1,
            sizex = 4,
            sizey = 4,
            passes = 1,
            colormultiply = 1,
            red = 1,
            green = 1,
            blue = 1,
        },
        ToyTownSettings = {
            ["passes"] = 20,
            ["height"] = 0.7,
        },
        ActiveLight = false,
        EffectFunction = nil,
        Overlay = Material("arctic_nvg/faint.png", "mips"),
        -- ScaleToSquare = false,
        Entity = "arctic_nvg_gpnvg_grayscale",
        Offset = Vector(0, 0, 0),
        OffsetAngle = Angle(0, 0, 0)
    },
    {
        ShortName = "nvg_gpnvg_thermal",
        VManipIn = "nvg_gpnvg_in",
        VManipOut = "nvg_gpnvg_out",
        Model = "models/arctic_nvgs/nvg_gpnvg.mdl",
        FullColor = false,
        EquipDelay = 1.325,
        ThermalVision = true,
        ThermalHighlight = Color(255, 0, 0),
        ColorCorrectSettings = {
            ["$pp_colour_addr"] = -0.1,
            ["$pp_colour_addg"] = -0.1,
            ["$pp_colour_addb"] = 0.1,
            ["$pp_colour_brightness"] = 0,
            ["$pp_colour_contrast"] = 1,
            ["$pp_colour_colour"] = 1,
            ["$pp_colour_mulr"] = 0,
            ["$pp_colour_mulg"] = 0,
            ["$pp_colour_mulb"] = 0,
        },
        EquipSound = "arctic_nvgs/nvg_on_1.wav",
        UnequipSound = "arctic_nvgs/nvg_off_1.wav",
        BloomSettings = {
            darken = 0,
            multiply = 1,
            sizex = 4,
            sizey = 4,
            passes = 1,
            colormultiply = 1,
            red = 1,
            green = 1,
            blue = 1,
        },
        ToyTownSettings = {
            ["passes"] = 20,
            ["height"] = 0.7,
        },
        ActiveLight = false,
        EffectFunction = nil,
        Overlay = Material("arctic_nvg/faint.png", "mips"),
        -- ScaleToSquare = false,
        Entity = "arctic_nvg_gpnvg_thermal",
        Offset = Vector(0, 0, 0),
        OffsetAngle = Angle(0, 0, 0)
    },
    {
        ShortName = "nvg_pnv10t",
        VManipIn = "nvg_pnv_in",
        VManipOut = "nvg_pnv_out",
        Model = "models/arctic_nvgs/nvg_pnv.mdl",
        FullColor = false,
        EquipDelay = 1.325,
        ColorCorrectSettings = {
            ["$pp_colour_addr"] = 0,
            ["$pp_colour_addg"] = 0.02,
            ["$pp_colour_addb"] = 0.02,
            ["$pp_colour_brightness"] = 0.01,
            ["$pp_colour_contrast"] = 4.5,
            ["$pp_colour_colour"] = 1,
            ["$pp_colour_mulr"] = 0,
            ["$pp_colour_mulg"] = 0,
            ["$pp_colour_mulb"] = 0,
        },
        EquipSound = "arctic_nvgs/nvg_on_1.wav",
        UnequipSound = "arctic_nvgs/nvg_off_1.wav",
        BloomSettings = {
            darken = 0,
            multiply = 1,
            sizex = 4,
            sizey = 4,
            passes = 1,
            colormultiply = 1,
            red = 1,
            green = 1,
            blue = 1,
        },
        ToyTownSettings = {
            ["passes"] = 20,
            ["height"] = 0.7,
        },
        ActiveLight = false,
        EffectFunction = nil,
        Overlay = Material("arctic_nvg/narrow.png", "mips"),
        -- ScaleToSquare = false,
        Entity = "arctic_nvg_pnv10",
        Offset = Vector(0, 0, 0),
        OffsetAngle = Angle(0, 0, 0)
    },
    {
        ShortName = "nvg_pnv10t_g",
        VManipIn = "nvg_pnv_in",
        VManipOut = "nvg_pnv_out",
        Model = "models/arctic_nvgs/nvg_pnv.mdl",
        FullColor = false,
        EquipDelay = 1.325,
        ColorCorrectSettings = {
            ["$pp_colour_addr"] = 0,
            ["$pp_colour_addg"] = 0.025,
            ["$pp_colour_addb"] = -0.05,
            ["$pp_colour_brightness"] = 0.01,
            ["$pp_colour_contrast"] = 4.5,
            ["$pp_colour_colour"] = 1,
            ["$pp_colour_mulr"] = 0,
            ["$pp_colour_mulg"] = 0,
            ["$pp_colour_mulb"] = 0,
        },
        EquipSound = "arctic_nvgs/nvg_on_1.wav",
        UnequipSound = "arctic_nvgs/nvg_off_1.wav",
        BloomSettings = {
            darken = 0,
            multiply = 1,
            sizex = 4,
            sizey = 4,
            passes = 1,
            colormultiply = 1,
            red = 1,
            green = 1,
            blue = 1,
        },
        ToyTownSettings = {
            ["passes"] = 20,
            ["height"] = 0.7,
        },
        ActiveLight = false,
        EffectFunction = nil,
        Overlay = Material("arctic_nvg/narrow.png", "mips"),
        -- ScaleToSquare = false,
        Entity = "arctic_nvg_pnv10_green",
        Offset = Vector(0, 0, 0),
        OffsetAngle = Angle(0, 0, 0)
    },
    {
        ShortName = "nvg_pnv10t_a",
        VManipIn = "nvg_pnv_in",
        VManipOut = "nvg_pnv_out",
        Model = "models/arctic_nvgs/nvg_pnv.mdl",
        FullColor = false,
        EquipDelay = 1.325,
        ColorCorrectSettings = {
            ["$pp_colour_addr"] = 0.03,
            ["$pp_colour_addg"] = 0.01,
            ["$pp_colour_addb"] = -0.1,
            ["$pp_colour_brightness"] = 0.01,
            ["$pp_colour_contrast"] = 4.5,
            ["$pp_colour_colour"] = 1,
            ["$pp_colour_mulr"] = 0,
            ["$pp_colour_mulg"] = 0,
            ["$pp_colour_mulb"] = 0,
        },
        EquipSound = "arctic_nvgs/nvg_on_1.wav",
        UnequipSound = "arctic_nvgs/nvg_off_1.wav",
        BloomSettings = {
            darken = 0,
            multiply = 1,
            sizex = 4,
            sizey = 4,
            passes = 1,
            colormultiply = 1,
            red = 1,
            green = 1,
            blue = 1,
        },
        ToyTownSettings = {
            ["passes"] = 20,
            ["height"] = 0.7,
        },
        ActiveLight = false,
        EffectFunction = nil,
        Overlay = Material("arctic_nvg/narrow.png", "mips"),
        -- ScaleToSquare = false,
        Entity = "arctic_nvg_pnv10_amber",
        Offset = Vector(0, 0, 0),
        OffsetAngle = Angle(0, 0, 0)
    },
    {
        ShortName = "nvg_pnv10t_r",
        VManipIn = "nvg_pnv_in",
        VManipOut = "nvg_pnv_out",
        Model = "models/arctic_nvgs/nvg_pnv.mdl",
        FullColor = false,
        EquipDelay = 1.325,
        ColorCorrectSettings = {
            ["$pp_colour_addr"] = 0.05,
            ["$pp_colour_addg"] = -0.05,
            ["$pp_colour_addb"] = -0.05,
            ["$pp_colour_brightness"] = 0.01,
            ["$pp_colour_contrast"] = 4.5,
            ["$pp_colour_colour"] = 1,
            ["$pp_colour_mulr"] = 0,
            ["$pp_colour_mulg"] = 0,
            ["$pp_colour_mulb"] = 0,
        },
        EquipSound = "arctic_nvgs/nvg_on_1.wav",
        UnequipSound = "arctic_nvgs/nvg_off_1.wav",
        BloomSettings = {
            darken = 0,
            multiply = 1,
            sizex = 4,
            sizey = 4,
            passes = 1,
            colormultiply = 1,
            red = 1,
            green = 1,
            blue = 1,
        },
        ToyTownSettings = {
            ["passes"] = 20,
            ["height"] = 0.7,
        },
        ActiveLight = false,
        EffectFunction = nil,
        Overlay = Material("arctic_nvg/narrow.png", "mips"),
        -- ScaleToSquare = false,
        Entity = "arctic_nvg_pnv10_red",
        Offset = Vector(0, 0, 0),
        OffsetAngle = Angle(0, 0, 0)
    },
    {
        ShortName = "nvg_pnv10t_b",
        VManipIn = "nvg_pnv_in",
        VManipOut = "nvg_pnv_out",
        Model = "models/arctic_nvgs/nvg_pnv.mdl",
        FullColor = false,
        EquipDelay = 1.325,
        ColorCorrectSettings = {
            ["$pp_colour_addr"] = -0.03,
            ["$pp_colour_addg"] = -0.03,
            ["$pp_colour_addb"] = 0.03,
            ["$pp_colour_brightness"] = 0.01,
            ["$pp_colour_contrast"] = 4.5,
            ["$pp_colour_colour"] = 1,
            ["$pp_colour_mulr"] = 0,
            ["$pp_colour_mulg"] = 0,
            ["$pp_colour_mulb"] = 0,
        },
        EquipSound = "arctic_nvgs/nvg_on_1.wav",
        UnequipSound = "arctic_nvgs/nvg_off_1.wav",
        BloomSettings = {
            darken = 0,
            multiply = 1,
            sizex = 4,
            sizey = 4,
            passes = 1,
            colormultiply = 1,
            red = 1,
            green = 1,
            blue = 1,
        },
        ToyTownSettings = {
            ["passes"] = 20,
            ["height"] = 0.7,
        },
        ActiveLight = false,
        EffectFunction = nil,
        Overlay = Material("arctic_nvg/narrow.png", "mips"),
        -- ScaleToSquare = false,
        Entity = "arctic_nvg_pnv10_blue",
        Offset = Vector(0, 0, 0),
        OffsetAngle = Angle(0, 0, 0)
    },
    {
        ShortName = "nvg_pnv10t_p",
        VManipIn = "nvg_pnv_in",
        VManipOut = "nvg_pnv_out",
        Model = "models/arctic_nvgs/nvg_pnv.mdl",
        FullColor = false,
        EquipDelay = 1.325,
        ColorCorrectSettings = {
            ["$pp_colour_addr"] = -0.01,
            ["$pp_colour_addg"] = -0.05,
            ["$pp_colour_addb"] = 0.02,
            ["$pp_colour_brightness"] = 0.01,
            ["$pp_colour_contrast"] = 4.5,
            ["$pp_colour_colour"] = 1,
            ["$pp_colour_mulr"] = 0,
            ["$pp_colour_mulg"] = 0,
            ["$pp_colour_mulb"] = 0,
        },
        EquipSound = "arctic_nvgs/nvg_on_1.wav",
        UnequipSound = "arctic_nvgs/nvg_off_1.wav",
        BloomSettings = {
            darken = 0,
            multiply = 1,
            sizex = 4,
            sizey = 4,
            passes = 1,
            colormultiply = 1,
            red = 1,
            green = 1,
            blue = 1,
        },
        ToyTownSettings = {
            ["passes"] = 20,
            ["height"] = 0.7,
        },
        ActiveLight = false,
        EffectFunction = nil,
        Overlay = Material("arctic_nvg/narrow.png", "mips"),
        -- ScaleToSquare = false,
        Entity = "arctic_nvg_pnv10_purple",
        Offset = Vector(0, 0, 0),
        OffsetAngle = Angle(0, 0, 0)
    },
    {
        ShortName = "nvg_pnv10t_c",
        VManipIn = "nvg_pnv_in",
        VManipOut = "nvg_pnv_out",
        Model = "models/arctic_nvgs/nvg_pnv.mdl",
        FullColor = false,
        EquipDelay = 1.325,
        ColorCorrectSettings = {
            ["$pp_colour_addr"] = -0.05,
            ["$pp_colour_addg"] = 0,
            ["$pp_colour_addb"] = 0,
            ["$pp_colour_brightness"] = 0.01,
            ["$pp_colour_contrast"] = 4.5,
            ["$pp_colour_colour"] = 1,
            ["$pp_colour_mulr"] = 0,
            ["$pp_colour_mulg"] = 0,
            ["$pp_colour_mulb"] = 0,
        },
        EquipSound = "arctic_nvgs/nvg_on_1.wav",
        UnequipSound = "arctic_nvgs/nvg_off_1.wav",
        BloomSettings = {
            darken = 0,
            multiply = 1,
            sizex = 4,
            sizey = 4,
            passes = 1,
            colormultiply = 1,
            red = 1,
            green = 1,
            blue = 1,
        },
        ToyTownSettings = {
            ["passes"] = 20,
            ["height"] = 0.7,
        },
        ActiveLight = false,
        EffectFunction = nil,
        Overlay = Material("arctic_nvg/narrow.png", "mips"),
        -- ScaleToSquare = false,
        Entity = "arctic_nvg_pnv10_cyan",
        Offset = Vector(0, 0, 0),
        OffsetAngle = Angle(0, 0, 0)
    },
    {
        ShortName = "nvg_pnv10t_ru",
        VManipIn = "nvg_pnv_in",
        VManipOut = "nvg_pnv_out",
        Model = "models/arctic_nvgs/nvg_pnv.mdl",
        FullColor = false,
        EquipDelay = 1.325,
        ColorCorrectSettings = {
            ["$pp_colour_addr"] = -0.05,
            ["$pp_colour_addg"] = 0.01,
            ["$pp_colour_addb"] = -0.1,
            ["$pp_colour_brightness"] = 0.01,
            ["$pp_colour_contrast"] = 4.5,
            ["$pp_colour_colour"] = 1,
            ["$pp_colour_mulr"] = 0,
            ["$pp_colour_mulg"] = 0,
            ["$pp_colour_mulb"] = 0,
        },
        EquipSound = "arctic_nvgs/nvg_on_1.wav",
        UnequipSound = "arctic_nvgs/nvg_off_1.wav",
        BloomSettings = {
            darken = 0,
            multiply = 1,
            sizex = 4,
            sizey = 4,
            passes = 1,
            colormultiply = 1,
            red = 1,
            green = 1,
            blue = 1,
        },
        ToyTownSettings = {
            ["passes"] = 20,
            ["height"] = 0.7,
        },
        ActiveLight = false,
        EffectFunction = nil,
        Overlay = Material("arctic_nvg/narrow.png", "mips"),
        -- ScaleToSquare = false,
        Entity = "arctic_nvg_pnv10_russian",
        Offset = Vector(0, 0, 0),
        OffsetAngle = Angle(0, 0, 0)
    },
    {
        ShortName = "nvg_pnv10t_t",
        VManipIn = "nvg_pnv_in",
        VManipOut = "nvg_pnv_out",
        Model = "models/arctic_nvgs/nvg_pnv.mdl",
        FullColor = false,
        EquipDelay = 1.325,
        ColorCorrectSettings = {
            ["$pp_colour_addr"] = -0.04,
            ["$pp_colour_addg"] = 0.02,
            ["$pp_colour_addb"] = 0.01,
            ["$pp_colour_brightness"] = 0.01,
            ["$pp_colour_contrast"] = 4.5,
            ["$pp_colour_colour"] = 1,
            ["$pp_colour_mulr"] = 0,
            ["$pp_colour_mulg"] = 0,
            ["$pp_colour_mulb"] = 0,
        },
        EquipSound = "arctic_nvgs/nvg_on_1.wav",
        UnequipSound = "arctic_nvgs/nvg_off_1.wav",
        BloomSettings = {
            darken = 0,
            multiply = 1,
            sizex = 4,
            sizey = 4,
            passes = 1,
            colormultiply = 1,
            red = 1,
            green = 1,
            blue = 1,
        },
        ToyTownSettings = {
            ["passes"] = 20,
            ["height"] = 0.7,
        },
        ActiveLight = false,
        EffectFunction = nil,
        Overlay = Material("arctic_nvg/narrow.png", "mips"),
        -- ScaleToSquare = false,
        Entity = "arctic_nvg_pnv10_teal",
        Offset = Vector(0, 0, 0),
        OffsetAngle = Angle(0, 0, 0)
    },
    {
        ShortName = "nvg_pnv10t_hp",
        VManipIn = "nvg_pnv_in",
        VManipOut = "nvg_pnv_out",
        Model = "models/arctic_nvgs/nvg_pnv.mdl",
        FullColor = false,
        EquipDelay = 1.325,
        ColorCorrectSettings = {
            ["$pp_colour_addr"] = 0.04,
            ["$pp_colour_addg"] = -0.05,
            ["$pp_colour_addb"] = 0.005,
            ["$pp_colour_brightness"] = 0.01,
            ["$pp_colour_contrast"] = 4.5,
            ["$pp_colour_colour"] = 1,
            ["$pp_colour_mulr"] = 0,
            ["$pp_colour_mulg"] = 0,
            ["$pp_colour_mulb"] = 0,
        },
        EquipSound = "arctic_nvgs/nvg_on_1.wav",
        UnequipSound = "arctic_nvgs/nvg_off_1.wav",
        BloomSettings = {
            darken = 0,
            multiply = 1,
            sizex = 4,
            sizey = 4,
            passes = 1,
            colormultiply = 1,
            red = 1,
            green = 1,
            blue = 1,
        },
        ToyTownSettings = {
            ["passes"] = 20,
            ["height"] = 0.7,
        },
        ActiveLight = false,
        EffectFunction = nil,
        Overlay = Material("arctic_nvg/narrow.png", "mips"),
        -- ScaleToSquare = false,
        Entity = "arctic_nvg_pnv10_hotpink",
        Offset = Vector(0, 0, 0),
        OffsetAngle = Angle(0, 0, 0)
    },
    {
        ShortName = "nvg_pnv10t_bw",
        VManipIn = "nvg_pnv_in",
        VManipOut = "nvg_pnv_out",
        Model = "models/arctic_nvgs/nvg_pnv.mdl",
        FullColor = false,
        EquipDelay = 1.325,
        ColorCorrectSettings = {
            ["$pp_colour_addr"] = 0,
            ["$pp_colour_addg"] = 0,
            ["$pp_colour_addb"] = 0,
            ["$pp_colour_brightness"] = 0.01,
            ["$pp_colour_contrast"] = 4.5,
            ["$pp_colour_colour"] = 1,
            ["$pp_colour_mulr"] = 0,
            ["$pp_colour_mulg"] = 0,
            ["$pp_colour_mulb"] = 0,
        },
        EquipSound = "arctic_nvgs/nvg_on_1.wav",
        UnequipSound = "arctic_nvgs/nvg_off_1.wav",
        BloomSettings = {
            darken = 0,
            multiply = 1,
            sizex = 4,
            sizey = 4,
            passes = 1,
            colormultiply = 1,
            red = 1,
            green = 1,
            blue = 1,
        },
        ToyTownSettings = {
            ["passes"] = 20,
            ["height"] = 0.7,
        },
        ActiveLight = false,
        EffectFunction = nil,
        Overlay = Material("arctic_nvg/narrow.png", "mips"),
        -- ScaleToSquare = false,
        Entity = "arctic_nvg_pnv10_grayscale",
        Offset = Vector(0, 0, 0),
        OffsetAngle = Angle(0, 0, 0)
    },
    {
        ShortName = "nvg_n15",
        VManipIn = "nvg_n15_in",
        VManipOut = "nvg_n15_out",
        Model = "models/arctic_nvgs/nvg_n15.mdl",
        FullColor = false,
        EquipDelay = 1.325,
        ColorCorrectSettings = {
            ["$pp_colour_addr"] = 0,
            ["$pp_colour_addg"] = 0.02,
            ["$pp_colour_addb"] = 0.02,
            ["$pp_colour_brightness"] = 0.01,
            ["$pp_colour_contrast"] = 4.5,
            ["$pp_colour_colour"] = 1,
            ["$pp_colour_mulr"] = 0,
            ["$pp_colour_mulg"] = 0,
            ["$pp_colour_mulb"] = 0,
        },
        EquipSound = "arctic_nvgs/nvg_on_1.wav",
        UnequipSound = "arctic_nvgs/nvg_off_1.wav",
        BloomSettings = {
            darken = 0,
            multiply = 1,
            sizex = 4,
            sizey = 4,
            passes = 1,
            colormultiply = 1,
            red = 1,
            green = 1,
            blue = 1,
        },
        ToyTownSettings = {
            ["passes"] = 20,
            ["height"] = 0.7,
        },
        ActiveLight = false,
        EffectFunction = nil,
        Overlay = Material("arctic_nvg/narrow.png", "mips"),
        -- ScaleToSquare = false,
        Entity = "arctic_nvg_n15",
        Offset = Vector(0, 0, 0),
        OffsetAngle = Angle(0, 0, 0)
    },
    {
        ShortName = "nvg_n15_g",
        VManipIn = "nvg_n15_in",
        VManipOut = "nvg_n15_out",
        Model = "models/arctic_nvgs/nvg_n15.mdl",
        FullColor = false,
        EquipDelay = 1.325,
        ColorCorrectSettings = {
            ["$pp_colour_addr"] = 0,
            ["$pp_colour_addg"] = 0.025,
            ["$pp_colour_addb"] = -0.05,
            ["$pp_colour_brightness"] = 0.01,
            ["$pp_colour_contrast"] = 4.5,
            ["$pp_colour_colour"] = 1,
            ["$pp_colour_mulr"] = 0,
            ["$pp_colour_mulg"] = 0,
            ["$pp_colour_mulb"] = 0,
        },
        EquipSound = "arctic_nvgs/nvg_on_1.wav",
        UnequipSound = "arctic_nvgs/nvg_off_1.wav",
        BloomSettings = {
            darken = 0,
            multiply = 1,
            sizex = 4,
            sizey = 4,
            passes = 1,
            colormultiply = 1,
            red = 1,
            green = 1,
            blue = 1,
        },
        ToyTownSettings = {
            ["passes"] = 20,
            ["height"] = 0.7,
        },
        ActiveLight = false,
        EffectFunction = nil,
        Overlay = Material("arctic_nvg/narrow.png", "mips"),
        -- ScaleToSquare = false,
        Entity = "arctic_nvg_n15_green",
        Offset = Vector(0, 0, 0),
        OffsetAngle = Angle(0, 0, 0)
    },
    {
        ShortName = "nvg_n15_a",
        VManipIn = "nvg_n15_in",
        VManipOut = "nvg_n15_out",
        Model = "models/arctic_nvgs/nvg_n15.mdl",
        FullColor = false,
        EquipDelay = 1.325,
        ColorCorrectSettings = {
            ["$pp_colour_addr"] = 0.03,
            ["$pp_colour_addg"] = 0.01,
            ["$pp_colour_addb"] = -0.1,
            ["$pp_colour_brightness"] = 0.01,
            ["$pp_colour_contrast"] = 4.5,
            ["$pp_colour_colour"] = 1,
            ["$pp_colour_mulr"] = 0,
            ["$pp_colour_mulg"] = 0,
            ["$pp_colour_mulb"] = 0,
        },
        EquipSound = "arctic_nvgs/nvg_on_1.wav",
        UnequipSound = "arctic_nvgs/nvg_off_1.wav",
        BloomSettings = {
            darken = 0,
            multiply = 1,
            sizex = 4,
            sizey = 4,
            passes = 1,
            colormultiply = 1,
            red = 1,
            green = 1,
            blue = 1,
        },
        ToyTownSettings = {
            ["passes"] = 20,
            ["height"] = 0.7,
        },
        ActiveLight = false,
        EffectFunction = nil,
        Overlay = Material("arctic_nvg/narrow.png", "mips"),
        -- ScaleToSquare = false,
        Entity = "arctic_nvg_n15_amber",
        Offset = Vector(0, 0, 0),
        OffsetAngle = Angle(0, 0, 0)
    },
    {
        ShortName = "nvg_n15_r",
        VManipIn = "nvg_n15_in",
        VManipOut = "nvg_n15_out",
        Model = "models/arctic_nvgs/nvg_n15.mdl",
        FullColor = false,
        EquipDelay = 1.325,
        ColorCorrectSettings = {
            ["$pp_colour_addr"] = 0.05,
            ["$pp_colour_addg"] = -0.05,
            ["$pp_colour_addb"] = -0.05,
            ["$pp_colour_brightness"] = 0.01,
            ["$pp_colour_contrast"] = 4.5,
            ["$pp_colour_colour"] = 1,
            ["$pp_colour_mulr"] = 0,
            ["$pp_colour_mulg"] = 0,
            ["$pp_colour_mulb"] = 0,
        },
        EquipSound = "arctic_nvgs/nvg_on_1.wav",
        UnequipSound = "arctic_nvgs/nvg_off_1.wav",
        BloomSettings = {
            darken = 0,
            multiply = 1,
            sizex = 4,
            sizey = 4,
            passes = 1,
            colormultiply = 1,
            red = 1,
            green = 1,
            blue = 1,
        },
        ToyTownSettings = {
            ["passes"] = 20,
            ["height"] = 0.7,
        },
        ActiveLight = false,
        EffectFunction = nil,
        Overlay = Material("arctic_nvg/narrow.png", "mips"),
        -- ScaleToSquare = false,
        Entity = "arctic_nvg_n15_red",
        Offset = Vector(0, 0, 0),
        OffsetAngle = Angle(0, 0, 0)
    },
    {
        ShortName = "nvg_n15_b",
        VManipIn = "nvg_n15_in",
        VManipOut = "nvg_n15_out",
        Model = "models/arctic_nvgs/nvg_n15.mdl",
        FullColor = false,
        EquipDelay = 1.325,
        ColorCorrectSettings = {
            ["$pp_colour_addr"] = -0.03,
            ["$pp_colour_addg"] = -0.03,
            ["$pp_colour_addb"] = 0.03,
            ["$pp_colour_brightness"] = 0.01,
            ["$pp_colour_contrast"] = 4.5,
            ["$pp_colour_colour"] = 1,
            ["$pp_colour_mulr"] = 0,
            ["$pp_colour_mulg"] = 0,
            ["$pp_colour_mulb"] = 0,
        },
        EquipSound = "arctic_nvgs/nvg_on_1.wav",
        UnequipSound = "arctic_nvgs/nvg_off_1.wav",
        BloomSettings = {
            darken = 0,
            multiply = 1,
            sizex = 4,
            sizey = 4,
            passes = 1,
            colormultiply = 1,
            red = 1,
            green = 1,
            blue = 1,
        },
        ToyTownSettings = {
            ["passes"] = 20,
            ["height"] = 0.7,
        },
        ActiveLight = false,
        EffectFunction = nil,
        Overlay = Material("arctic_nvg/narrow.png", "mips"),
        -- ScaleToSquare = false,
        Entity = "arctic_nvg_n15_blue",
        Offset = Vector(0, 0, 0),
        OffsetAngle = Angle(0, 0, 0)
    },
    {
        ShortName = "nvg_n15_p",
        VManipIn = "nvg_n15_in",
        VManipOut = "nvg_n15_out",
        Model = "models/arctic_nvgs/nvg_n15.mdl",
        FullColor = false,
        EquipDelay = 1.325,
        ColorCorrectSettings = {
            ["$pp_colour_addr"] = -0.01,
            ["$pp_colour_addg"] = -0.05,
            ["$pp_colour_addb"] = 0.02,
            ["$pp_colour_brightness"] = 0.01,
            ["$pp_colour_contrast"] = 4.5,
            ["$pp_colour_colour"] = 1,
            ["$pp_colour_mulr"] = 0,
            ["$pp_colour_mulg"] = 0,
            ["$pp_colour_mulb"] = 0,
        },
        EquipSound = "arctic_nvgs/nvg_on_1.wav",
        UnequipSound = "arctic_nvgs/nvg_off_1.wav",
        BloomSettings = {
            darken = 0,
            multiply = 1,
            sizex = 4,
            sizey = 4,
            passes = 1,
            colormultiply = 1,
            red = 1,
            green = 1,
            blue = 1,
        },
        ToyTownSettings = {
            ["passes"] = 20,
            ["height"] = 0.7,
        },
        ActiveLight = false,
        EffectFunction = nil,
        Overlay = Material("arctic_nvg/narrow.png", "mips"),
        -- ScaleToSquare = false,
        Entity = "arctic_nvg_n15_purple",
        Offset = Vector(0, 0, 0),
        OffsetAngle = Angle(0, 0, 0)
    },
    {
        ShortName = "nvg_n15_c",
        VManipIn = "nvg_n15_in",
        VManipOut = "nvg_n15_out",
        Model = "models/arctic_nvgs/nvg_n15.mdl",
        FullColor = false,
        EquipDelay = 1.325,
        ColorCorrectSettings = {
            ["$pp_colour_addr"] = -0.05,
            ["$pp_colour_addg"] = 0,
            ["$pp_colour_addb"] = 0,
            ["$pp_colour_brightness"] = 0.01,
            ["$pp_colour_contrast"] = 4.5,
            ["$pp_colour_colour"] = 1,
            ["$pp_colour_mulr"] = 0,
            ["$pp_colour_mulg"] = 0,
            ["$pp_colour_mulb"] = 0,
        },
        EquipSound = "arctic_nvgs/nvg_on_1.wav",
        UnequipSound = "arctic_nvgs/nvg_off_1.wav",
        BloomSettings = {
            darken = 0,
            multiply = 1,
            sizex = 4,
            sizey = 4,
            passes = 1,
            colormultiply = 1,
            red = 1,
            green = 1,
            blue = 1,
        },
        ToyTownSettings = {
            ["passes"] = 20,
            ["height"] = 0.7,
        },
        ActiveLight = false,
        EffectFunction = nil,
        Overlay = Material("arctic_nvg/narrow.png", "mips"),
        -- ScaleToSquare = false,
        Entity = "arctic_nvg_n15_cyan",
        Offset = Vector(0, 0, 0),
        OffsetAngle = Angle(0, 0, 0)
    },
    {
        ShortName = "nvg_n15_ru",
        VManipIn = "nvg_n15_in",
        VManipOut = "nvg_n15_out",
        Model = "models/arctic_nvgs/nvg_n15.mdl",
        FullColor = false,
        EquipDelay = 1.325,
        ColorCorrectSettings = {
            ["$pp_colour_addr"] = -0.05,
            ["$pp_colour_addg"] = 0.01,
            ["$pp_colour_addb"] = -0.1,
            ["$pp_colour_brightness"] = 0.01,
            ["$pp_colour_contrast"] = 4.5,
            ["$pp_colour_colour"] = 1,
            ["$pp_colour_mulr"] = 0,
            ["$pp_colour_mulg"] = 0,
            ["$pp_colour_mulb"] = 0,
        },
        EquipSound = "arctic_nvgs/nvg_on_1.wav",
        UnequipSound = "arctic_nvgs/nvg_off_1.wav",
        BloomSettings = {
            darken = 0,
            multiply = 1,
            sizex = 4,
            sizey = 4,
            passes = 1,
            colormultiply = 1,
            red = 1,
            green = 1,
            blue = 1,
        },
        ToyTownSettings = {
            ["passes"] = 20,
            ["height"] = 0.7,
        },
        ActiveLight = false,
        EffectFunction = nil,
        Overlay = Material("arctic_nvg/narrow.png", "mips"),
        -- ScaleToSquare = false,
        Entity = "arctic_nvg_n15_russian",
        Offset = Vector(0, 0, 0),
        OffsetAngle = Angle(0, 0, 0)
    },
    {
        ShortName = "nvg_n15_t",
        VManipIn = "nvg_n15_in",
        VManipOut = "nvg_n15_out",
        Model = "models/arctic_nvgs/nvg_n15.mdl",
        FullColor = false,
        EquipDelay = 1.325,
        ColorCorrectSettings = {
            ["$pp_colour_addr"] = -0.04,
            ["$pp_colour_addg"] = 0.02,
            ["$pp_colour_addb"] = 0.01,
            ["$pp_colour_brightness"] = 0.01,
            ["$pp_colour_contrast"] = 4.5,
            ["$pp_colour_colour"] = 1,
            ["$pp_colour_mulr"] = 0,
            ["$pp_colour_mulg"] = 0,
            ["$pp_colour_mulb"] = 0,
        },
        EquipSound = "arctic_nvgs/nvg_on_1.wav",
        UnequipSound = "arctic_nvgs/nvg_off_1.wav",
        BloomSettings = {
            darken = 0,
            multiply = 1,
            sizex = 4,
            sizey = 4,
            passes = 1,
            colormultiply = 1,
            red = 1,
            green = 1,
            blue = 1,
        },
        ToyTownSettings = {
            ["passes"] = 20,
            ["height"] = 0.7,
        },
        ActiveLight = false,
        EffectFunction = nil,
        Overlay = Material("arctic_nvg/narrow.png", "mips"),
        -- ScaleToSquare = false,
        Entity = "arctic_nvg_n15_teal",
        Offset = Vector(0, 0, 0),
        OffsetAngle = Angle(0, 0, 0)
    },
    {
        ShortName = "nvg_n15_hp",
        VManipIn = "nvg_n15_in",
        VManipOut = "nvg_n15_out",
        Model = "models/arctic_nvgs/nvg_n15.mdl",
        FullColor = false,
        EquipDelay = 1.325,
        ColorCorrectSettings = {
            ["$pp_colour_addr"] = 0.04,
            ["$pp_colour_addg"] = -0.05,
            ["$pp_colour_addb"] = 0.005,
            ["$pp_colour_brightness"] = 0.01,
            ["$pp_colour_contrast"] = 4.5,
            ["$pp_colour_colour"] = 1,
            ["$pp_colour_mulr"] = 0,
            ["$pp_colour_mulg"] = 0,
            ["$pp_colour_mulb"] = 0,
        },
        EquipSound = "arctic_nvgs/nvg_on_1.wav",
        UnequipSound = "arctic_nvgs/nvg_off_1.wav",
        BloomSettings = {
            darken = 0,
            multiply = 1,
            sizex = 4,
            sizey = 4,
            passes = 1,
            colormultiply = 1,
            red = 1,
            green = 1,
            blue = 1,
        },
        ToyTownSettings = {
            ["passes"] = 20,
            ["height"] = 0.7,
        },
        ActiveLight = false,
        EffectFunction = nil,
        Overlay = Material("arctic_nvg/narrow.png", "mips"),
        -- ScaleToSquare = false,
        Entity = "arctic_nvg_n15_hotpink",
        Offset = Vector(0, 0, 0),
        OffsetAngle = Angle(0, 0, 0)
    },
    {
        ShortName = "nvg_n15_bw",
        VManipIn = "nvg_n15_in",
        VManipOut = "nvg_n15_out",
        Model = "models/arctic_nvgs/nvg_n15.mdl",
        FullColor = false,
        EquipDelay = 1.325,
        ColorCorrectSettings = {
            ["$pp_colour_addr"] = 0,
            ["$pp_colour_addg"] = 0,
            ["$pp_colour_addb"] = 0,
            ["$pp_colour_brightness"] = 0.01,
            ["$pp_colour_contrast"] = 4.5,
            ["$pp_colour_colour"] = 1,
            ["$pp_colour_mulr"] = 0,
            ["$pp_colour_mulg"] = 0,
            ["$pp_colour_mulb"] = 0,
        },
        EquipSound = "arctic_nvgs/nvg_on_1.wav",
        UnequipSound = "arctic_nvgs/nvg_off_1.wav",
        BloomSettings = {
            darken = 0,
            multiply = 1,
            sizex = 4,
            sizey = 4,
            passes = 1,
            colormultiply = 1,
            red = 1,
            green = 1,
            blue = 1,
        },
        ToyTownSettings = {
            ["passes"] = 20,
            ["height"] = 0.7,
        },
        ActiveLight = false,
        EffectFunction = nil,
        Overlay = Material("arctic_nvg/narrow.png", "mips"),
        -- ScaleToSquare = false,
        Entity = "arctic_nvg_n15_grayscale",
        Offset = Vector(0, 0, 0),
        OffsetAngle = Angle(0, 0, 0)
    },
    {
        ShortName = "nvg_n15_fc",
        VManipIn = "nvg_n15_in",
        VManipOut = "nvg_n15_out",
        Model = "models/arctic_nvgs/nvg_n15.mdl",
        FullColor = true,
        EquipDelay = 1.325,
        ColorCorrectSettings = {
            ["$pp_colour_addr"] = 0,
            ["$pp_colour_addg"] = 0,
            ["$pp_colour_addb"] = 0,
            ["$pp_colour_brightness"] = 0.01,
            ["$pp_colour_contrast"] = 4.5,
            ["$pp_colour_colour"] = 1,
            ["$pp_colour_mulr"] = 0,
            ["$pp_colour_mulg"] = 0,
            ["$pp_colour_mulb"] = 0,
        },
        EquipSound = "arctic_nvgs/nvg_on_1.wav",
        UnequipSound = "arctic_nvgs/nvg_off_1.wav",
        BloomSettings = {
            darken = 0,
            multiply = 2,
            sizex = 4,
            sizey = 4,
            passes = 1,
            colormultiply = 1,
            red = 1,
            green = 1,
            blue = 1,
        },
        ToyTownSettings = {
            ["passes"] = 20,
            ["height"] = 0.7,
        },
        ActiveLight = false,
        EffectFunction = nil,
        Overlay = Material("arctic_nvg/narrow.png", "mips"),
        -- ScaleToSquare = false,
        Entity = "arctic_nvg_n15_fullcolor",
        Offset = Vector(0, 0, 0),
        OffsetAngle = Angle(0, 0, 0)
    },
    {
        ShortName = "nvg_pvs14",
        VManipIn = "nvg_pvs14_in",
        VManipOut = "nvg_pvs14_out",
        EquipDelay = 1.325,
        Model = "models/arctic_nvgs/nvg_pvs14.mdl",
        FullColor = false,
        ColorCorrectSettings = {
            ["$pp_colour_addr"] = 0,
            ["$pp_colour_addg"] = 0.02,
            ["$pp_colour_addb"] = 0.02,
            ["$pp_colour_brightness"] = 0.01,
            ["$pp_colour_contrast"] = 4.5,
            ["$pp_colour_colour"] = 1,
            ["$pp_colour_mulr"] = 0,
            ["$pp_colour_mulg"] = 0,
            ["$pp_colour_mulb"] = 0,
        },
        EquipSound = "arctic_nvgs/nvg_on_1.wav",
        UnequipSound = "arctic_nvgs/nvg_off_1.wav",
        BloomSettings = {
            darken = 0,
            multiply = 1,
            sizex = 4,
            sizey = 4,
            passes = 1,
            colormultiply = 1,
            red = 1,
            green = 1,
            blue = 1,
        },
        ToyTownSettings = {
            ["passes"] = 20,
            ["height"] = 0.7,
        },
        ActiveLight = false,
        EffectFunction = nil,
        Overlay = Material("arctic_nvg/narrow.png", "mips"),
        ScaleToSquare = false,
        Entity = "arctic_nvg_pvs14",
        Offset = Vector(0, 0, 0),
        OffsetAngle = Angle(0, 0, 0)
    },
    {
        ShortName = "nvg_pvs14_g",
        VManipIn = "nvg_pvs14_in",
        VManipOut = "nvg_pvs14_out",
        EquipDelay = 1.325,
        Model = "models/arctic_nvgs/nvg_pvs14.mdl",
        FullColor = false,
        ColorCorrectSettings = {
            ["$pp_colour_addr"] = 0,
            ["$pp_colour_addg"] = 0.025,
            ["$pp_colour_addb"] = -0.05,
            ["$pp_colour_brightness"] = 0.01,
            ["$pp_colour_contrast"] = 4.5,
            ["$pp_colour_colour"] = 1,
            ["$pp_colour_mulr"] = 0,
            ["$pp_colour_mulg"] = 0,
            ["$pp_colour_mulb"] = 0,
        },
        EquipSound = "arctic_nvgs/nvg_on_1.wav",
        UnequipSound = "arctic_nvgs/nvg_off_1.wav",
        BloomSettings = {
            darken = 0,
            multiply = 1,
            sizex = 4,
            sizey = 4,
            passes = 1,
            colormultiply = 1,
            red = 1,
            green = 1,
            blue = 1,
        },
        ToyTownSettings = {
            ["passes"] = 20,
            ["height"] = 0.7,
        },
        ActiveLight = false,
        EffectFunction = nil,
        Overlay = Material("arctic_nvg/narrow.png", "mips"),
        ScaleToSquare = false,
        Entity = "arctic_nvg_pvs14_green",
        Offset = Vector(0, 0, 0),
        OffsetAngle = Angle(0, 0, 0)
    },
    {
        ShortName = "nvg_pvs14_a",
        VManipIn = "nvg_pvs14_in",
        VManipOut = "nvg_pvs14_out",
        EquipDelay = 1.325,
        Model = "models/arctic_nvgs/nvg_pvs14.mdl",
        FullColor = false,
        ColorCorrectSettings = {
            ["$pp_colour_addr"] = 0.03,
            ["$pp_colour_addg"] = 0.01,
            ["$pp_colour_addb"] = -0.1,
            ["$pp_colour_brightness"] = 0.01,
            ["$pp_colour_contrast"] = 4.5,
            ["$pp_colour_colour"] = 1,
            ["$pp_colour_mulr"] = 0,
            ["$pp_colour_mulg"] = 0,
            ["$pp_colour_mulb"] = 0,
        },
        EquipSound = "arctic_nvgs/nvg_on_1.wav",
        UnequipSound = "arctic_nvgs/nvg_off_1.wav",
        BloomSettings = {
            darken = 0,
            multiply = 1,
            sizex = 4,
            sizey = 4,
            passes = 1,
            colormultiply = 1,
            red = 1,
            green = 1,
            blue = 1,
        },
        ToyTownSettings = {
            ["passes"] = 20,
            ["height"] = 0.7,
        },
        ActiveLight = false,
        EffectFunction = nil,
        Overlay = Material("arctic_nvg/narrow.png", "mips"),
        ScaleToSquare = false,
        Entity = "arctic_nvg_pvs14_amber",
        Offset = Vector(0, 0, 0),
        OffsetAngle = Angle(0, 0, 0)
    },
    {
        ShortName = "nvg_pvs14_r",
        VManipIn = "nvg_pvs14_in",
        VManipOut = "nvg_pvs14_out",
        EquipDelay = 1.325,
        Model = "models/arctic_nvgs/nvg_pvs14.mdl",
        FullColor = false,
        ColorCorrectSettings = {
            ["$pp_colour_addr"] = 0.05,
            ["$pp_colour_addg"] = -0.05,
            ["$pp_colour_addb"] = -0.05,
            ["$pp_colour_brightness"] = 0.01,
            ["$pp_colour_contrast"] = 4.5,
            ["$pp_colour_colour"] = 1,
            ["$pp_colour_mulr"] = 0,
            ["$pp_colour_mulg"] = 0,
            ["$pp_colour_mulb"] = 0,
        },
        EquipSound = "arctic_nvgs/nvg_on_1.wav",
        UnequipSound = "arctic_nvgs/nvg_off_1.wav",
        BloomSettings = {
            darken = 0,
            multiply = 1,
            sizex = 4,
            sizey = 4,
            passes = 1,
            colormultiply = 1,
            red = 1,
            green = 1,
            blue = 1,
        },
        ToyTownSettings = {
            ["passes"] = 20,
            ["height"] = 0.7,
        },
        ActiveLight = false,
        EffectFunction = nil,
        Overlay = Material("arctic_nvg/narrow.png", "mips"),
        ScaleToSquare = false,
        Entity = "arctic_nvg_pvs14_red",
        Offset = Vector(0, 0, 0),
        OffsetAngle = Angle(0, 0, 0)
    },
    {
        ShortName = "nvg_pvs14_b",
        VManipIn = "nvg_pvs14_in",
        VManipOut = "nvg_pvs14_out",
        EquipDelay = 1.325,
        Model = "models/arctic_nvgs/nvg_pvs14.mdl",
        FullColor = false,
        ColorCorrectSettings = {
            ["$pp_colour_addr"] = -0.03,
            ["$pp_colour_addg"] = -0.03,
            ["$pp_colour_addb"] = 0.03,
            ["$pp_colour_brightness"] = 0.01,
            ["$pp_colour_contrast"] = 4.5,
            ["$pp_colour_colour"] = 1,
            ["$pp_colour_mulr"] = 0,
            ["$pp_colour_mulg"] = 0,
            ["$pp_colour_mulb"] = 0,
        },
        EquipSound = "arctic_nvgs/nvg_on_1.wav",
        UnequipSound = "arctic_nvgs/nvg_off_1.wav",
        BloomSettings = {
            darken = 0,
            multiply = 1,
            sizex = 4,
            sizey = 4,
            passes = 1,
            colormultiply = 1,
            red = 1,
            green = 1,
            blue = 1,
        },
        ToyTownSettings = {
            ["passes"] = 20,
            ["height"] = 0.7,
        },
        ActiveLight = false,
        EffectFunction = nil,
        Overlay = Material("arctic_nvg/narrow.png", "mips"),
        ScaleToSquare = false,
        Entity = "arctic_nvg_pvs14_blue",
        Offset = Vector(0, 0, 0),
        OffsetAngle = Angle(0, 0, 0)
    },
    {
        ShortName = "nvg_pvs14_p",
        VManipIn = "nvg_pvs14_in",
        VManipOut = "nvg_pvs14_out",
        EquipDelay = 1.325,
        Model = "models/arctic_nvgs/nvg_pvs14.mdl",
        FullColor = false,
        ColorCorrectSettings = {
            ["$pp_colour_addr"] = -0.01,
            ["$pp_colour_addg"] = -0.05,
            ["$pp_colour_addb"] = 0.02,
            ["$pp_colour_brightness"] = 0.01,
            ["$pp_colour_contrast"] = 4.5,
            ["$pp_colour_colour"] = 1,
            ["$pp_colour_mulr"] = 0,
            ["$pp_colour_mulg"] = 0,
            ["$pp_colour_mulb"] = 0,
        },
        EquipSound = "arctic_nvgs/nvg_on_1.wav",
        UnequipSound = "arctic_nvgs/nvg_off_1.wav",
        BloomSettings = {
            darken = 0,
            multiply = 1,
            sizex = 4,
            sizey = 4,
            passes = 1,
            colormultiply = 1,
            red = 1,
            green = 1,
            blue = 1,
        },
        ToyTownSettings = {
            ["passes"] = 20,
            ["height"] = 0.7,
        },
        ActiveLight = false,
        EffectFunction = nil,
        Overlay = Material("arctic_nvg/narrow.png", "mips"),
        ScaleToSquare = false,
        Entity = "arctic_nvg_pvs14_purple",
        Offset = Vector(0, 0, 0),
        OffsetAngle = Angle(0, 0, 0)
    },
    {
        ShortName = "nvg_pvs14_c",
        VManipIn = "nvg_pvs14_in",
        VManipOut = "nvg_pvs14_out",
        EquipDelay = 1.325,
        Model = "models/arctic_nvgs/nvg_pvs14.mdl",
        FullColor = false,
        ColorCorrectSettings = {
            ["$pp_colour_addr"] = -0.05,
            ["$pp_colour_addg"] = 0,
            ["$pp_colour_addb"] = 0,
            ["$pp_colour_brightness"] = 0.01,
            ["$pp_colour_contrast"] = 4.5,
            ["$pp_colour_colour"] = 1,
            ["$pp_colour_mulr"] = 0,
            ["$pp_colour_mulg"] = 0,
            ["$pp_colour_mulb"] = 0,
        },
        EquipSound = "arctic_nvgs/nvg_on_1.wav",
        UnequipSound = "arctic_nvgs/nvg_off_1.wav",
        BloomSettings = {
            darken = 0,
            multiply = 1,
            sizex = 4,
            sizey = 4,
            passes = 1,
            colormultiply = 1,
            red = 1,
            green = 1,
            blue = 1,
        },
        ToyTownSettings = {
            ["passes"] = 20,
            ["height"] = 0.7,
        },
        ActiveLight = false,
        EffectFunction = nil,
        Overlay = Material("arctic_nvg/narrow.png", "mips"),
        ScaleToSquare = false,
        Entity = "arctic_nvg_pvs14_cyan",
        Offset = Vector(0, 0, 0),
        OffsetAngle = Angle(0, 0, 0)
    },
    {
        ShortName = "nvg_pvs14_ru",
        VManipIn = "nvg_pvs14_in",
        VManipOut = "nvg_pvs14_out",
        EquipDelay = 1.325,
        Model = "models/arctic_nvgs/nvg_pvs14.mdl",
        FullColor = false,
        ColorCorrectSettings = {
            ["$pp_colour_addr"] = -0.05,
            ["$pp_colour_addg"] = 0.01,
            ["$pp_colour_addb"] = -0.1,
            ["$pp_colour_brightness"] = 0.01,
            ["$pp_colour_contrast"] = 4.5,
            ["$pp_colour_colour"] = 1,
            ["$pp_colour_mulr"] = 0,
            ["$pp_colour_mulg"] = 0,
            ["$pp_colour_mulb"] = 0,
        },
        EquipSound = "arctic_nvgs/nvg_on_1.wav",
        UnequipSound = "arctic_nvgs/nvg_off_1.wav",
        BloomSettings = {
            darken = 0,
            multiply = 1,
            sizex = 4,
            sizey = 4,
            passes = 1,
            colormultiply = 1,
            red = 1,
            green = 1,
            blue = 1,
        },
        ToyTownSettings = {
            ["passes"] = 20,
            ["height"] = 0.7,
        },
        ActiveLight = false,
        EffectFunction = nil,
        Overlay = Material("arctic_nvg/narrow.png", "mips"),
        ScaleToSquare = false,
        Entity = "arctic_nvg_pvs14_russian",
        Offset = Vector(0, 0, 0),
        OffsetAngle = Angle(0, 0, 0)
    },
    {
        ShortName = "nvg_pvs14_t",
        VManipIn = "nvg_pvs14_in",
        VManipOut = "nvg_pvs14_out",
        EquipDelay = 1.325,
        Model = "models/arctic_nvgs/nvg_pvs14.mdl",
        FullColor = false,
        ColorCorrectSettings = {
            ["$pp_colour_addr"] = -0.04,
            ["$pp_colour_addg"] = 0.02,
            ["$pp_colour_addb"] = 0.01,
            ["$pp_colour_brightness"] = 0.01,
            ["$pp_colour_contrast"] = 4.5,
            ["$pp_colour_colour"] = 1,
            ["$pp_colour_mulr"] = 0,
            ["$pp_colour_mulg"] = 0,
            ["$pp_colour_mulb"] = 0,
        },
        EquipSound = "arctic_nvgs/nvg_on_1.wav",
        UnequipSound = "arctic_nvgs/nvg_off_1.wav",
        BloomSettings = {
            darken = 0,
            multiply = 1,
            sizex = 4,
            sizey = 4,
            passes = 1,
            colormultiply = 1,
            red = 1,
            green = 1,
            blue = 1,
        },
        ToyTownSettings = {
            ["passes"] = 20,
            ["height"] = 0.7,
        },
        ActiveLight = false,
        EffectFunction = nil,
        Overlay = Material("arctic_nvg/narrow.png", "mips"),
        ScaleToSquare = false,
        Entity = "arctic_nvg_pvs14_teal",
        Offset = Vector(0, 0, 0),
        OffsetAngle = Angle(0, 0, 0)
    },
    {
        ShortName = "nvg_pvs14_hp",
        VManipIn = "nvg_pvs14_in",
        VManipOut = "nvg_pvs14_out",
        EquipDelay = 1.325,
        Model = "models/arctic_nvgs/nvg_pvs14.mdl",
        FullColor = false,
        ColorCorrectSettings = {
            ["$pp_colour_addr"] = 0.04,
            ["$pp_colour_addg"] = -0.05,
            ["$pp_colour_addb"] = 0.005,
            ["$pp_colour_brightness"] = 0.01,
            ["$pp_colour_contrast"] = 4.5,
            ["$pp_colour_colour"] = 1,
            ["$pp_colour_mulr"] = 0,
            ["$pp_colour_mulg"] = 0,
            ["$pp_colour_mulb"] = 0,
        },
        EquipSound = "arctic_nvgs/nvg_on_1.wav",
        UnequipSound = "arctic_nvgs/nvg_off_1.wav",
        BloomSettings = {
            darken = 0,
            multiply = 1,
            sizex = 4,
            sizey = 4,
            passes = 1,
            colormultiply = 1,
            red = 1,
            green = 1,
            blue = 1,
        },
        ToyTownSettings = {
            ["passes"] = 20,
            ["height"] = 0.7,
        },
        ActiveLight = false,
        EffectFunction = nil,
        Overlay = Material("arctic_nvg/narrow.png", "mips"),
        ScaleToSquare = false,
        Entity = "arctic_nvg_pvs14_hotpink",
        Offset = Vector(0, 0, 0),
        OffsetAngle = Angle(0, 0, 0)
    },
    {
        ShortName = "nvg_pvs14_bw",
        VManipIn = "nvg_pvs14_in",
        VManipOut = "nvg_pvs14_out",
        EquipDelay = 1.325,
        Model = "models/arctic_nvgs/nvg_pvs14.mdl",
        FullColor = false,
        ColorCorrectSettings = {
            ["$pp_colour_addr"] = 0,
            ["$pp_colour_addg"] = 0,
            ["$pp_colour_addb"] = 0,
            ["$pp_colour_brightness"] = 0.01,
            ["$pp_colour_contrast"] = 4.5,
            ["$pp_colour_colour"] = 1,
            ["$pp_colour_mulr"] = 0,
            ["$pp_colour_mulg"] = 0,
            ["$pp_colour_mulb"] = 0,
        },
        EquipSound = "arctic_nvgs/nvg_on_1.wav",
        UnequipSound = "arctic_nvgs/nvg_off_1.wav",
        BloomSettings = {
            darken = 0,
            multiply = 1,
            sizex = 4,
            sizey = 4,
            passes = 1,
            colormultiply = 1,
            red = 1,
            green = 1,
            blue = 1,
        },
        ToyTownSettings = {
            ["passes"] = 20,
            ["height"] = 0.7,
        },
        ActiveLight = false,
        EffectFunction = nil,
        Overlay = Material("arctic_nvg/narrow.png", "mips"),
        ScaleToSquare = false,
        Entity = "arctic_nvg_pvs14_grayscale",
        Offset = Vector(0, 0, 0),
        OffsetAngle = Angle(0, 0, 0)
    },
    {
        ShortName = "nvg_t7",
        VManipIn = "nvg_t7_in",
        VManipOut = "nvg_t7_out",
        EquipDelay = 1.325,
        Model = "models/arctic_nvgs/nvg_t7.mdl",
        FullColor = false,
        ColorCorrectSettings = {
            ["$pp_colour_addr"] = -0.1,
            ["$pp_colour_addg"] = -0.1,
            ["$pp_colour_addb"] = -0.1,
            ["$pp_colour_brightness"] = 0.1,
            ["$pp_colour_contrast"] = 2.5,
            ["$pp_colour_colour"] = 1,
            ["$pp_colour_mulr"] = 0,
            ["$pp_colour_mulg"] = 0,
            ["$pp_colour_mulb"] = 0,
        },
        EquipSound = "arctic_nvgs/nvg_on_1.wav",
        UnequipSound = "arctic_nvgs/nvg_off_1.wav",
        BloomSettings = {
            darken = 0,
            multiply = 1,
            sizex = 4,
            sizey = 4,
            passes = 1,
            colormultiply = 1,
            red = 1,
            green = 1,
            blue = 1,
        },
        ToyTownSettings = {
            ["passes"] = 20,
            ["height"] = 0.7,
        },
        ThermalVision = true,
        ThermalHighlight = Color(255, 0, 0),
        ActiveLight = false,
        EffectFunction = nil,
        Overlay = Material("arctic_nvg/binocular.png", "mips"),
        ScaleToSquare = false,
        Entity = "arctic_nvg_t7",
        Offset = Vector(0, 0, 0),
        OffsetAngle = Angle(0, 0, 0)
    },
    {
        ShortName = "nvg_t7_p",
        VManipIn = "nvg_t7_in",
        VManipOut = "nvg_t7_out",
        EquipDelay = 1.325,
        Model = "models/arctic_nvgs/nvg_t7.mdl",
        FullColor = false,
        ColorCorrectSettings = {
            ["$pp_colour_addr"] = -0.03,
            ["$pp_colour_addg"] = -0.1,
            ["$pp_colour_addb"] = 0.01,
            ["$pp_colour_brightness"] = 0.001,
            ["$pp_colour_contrast"] = 2.5,
            ["$pp_colour_colour"] = 1,
            ["$pp_colour_mulr"] = 0,
            ["$pp_colour_mulg"] = 0,
            ["$pp_colour_mulb"] = 0,
        },
        EquipSound = "arctic_nvgs/nvg_on_1.wav",
        UnequipSound = "arctic_nvgs/nvg_off_1.wav",
        BloomSettings = {
            darken = 0,
            multiply = 1,
            sizex = 4,
            sizey = 4,
            passes = 1,
            colormultiply = 1,
            red = 1,
            green = 1,
            blue = 1,
        },
        ToyTownSettings = {
            ["passes"] = 20,
            ["height"] = 0.7,
        },
        ThermalVision = true,
        ThermalHighlight = Color(255, 0, 0),
        ActiveLight = false,
        EffectFunction = nil,
        Overlay = Material("arctic_nvg/binocular.png", "mips"),
        ScaleToSquare = false,
        Entity = "arctic_nvg_t7_purple",
        Offset = Vector(0, 0, 0),
        OffsetAngle = Angle(0, 0, 0)
    },
    {
        ShortName = "shades",
        VManipIn = "nvg_aviators_in",
        VManipOut = "nvg_aviators_out",
        EquipDelay = 1.41,
        UnequipDelay = 0.25,
        NoBrightenWorld = true,
        Model = "models/arctic_nvgs/aviators.mdl",
        FullColor = true,
        NoFade = true,
        ColorCorrectSettings = {
            ["$pp_colour_addr"] = 0,
            ["$pp_colour_addg"] = 0,
            ["$pp_colour_addb"] = 0,
            ["$pp_colour_brightness"] = -0.05,
            ["$pp_colour_contrast"] = 1,
            ["$pp_colour_colour"] = 1,
            ["$pp_colour_mulr"] = 0,
            ["$pp_colour_mulg"] = 0,
            ["$pp_colour_mulb"] = 0,
        },
        EquipSound = "",
        UnequipSound = "",
        Overlay = Material("arctic_nvg/shades.png"),
        ScaleToSquare = false,
        Entity = "arctic_nvg_shades",
        Offset = Vector(-0.5, 0, 0),
        OffsetAngle = Angle(0, 0, 0)
    },
    {
        ShortName = "shades_wp",
        VManipIn = "nvg_aviators_in",
        VManipOut = "nvg_aviators_out",
        EquipDelay = 1.41,
        UnequipDelay = 0.25,
        NoBrightenWorld = true,
        Model = "models/arctic_nvgs/aviators.mdl",
        FullColor = false,
        NoFade = false,
        ColorCorrectSettings = {
            ["$pp_colour_addr"] = 0,
            ["$pp_colour_addg"] = 0.02,
            ["$pp_colour_addb"] = 0.02,
            ["$pp_colour_brightness"] = 0.01,
            ["$pp_colour_contrast"] = 4.5,
            ["$pp_colour_colour"] = 1,
            ["$pp_colour_mulr"] = 0,
            ["$pp_colour_mulg"] = 0,
            ["$pp_colour_mulb"] = 0,
        },
        BloomSettings = {
            darken = 0,
            multiply = 1,
            sizex = 4,
            sizey = 4,
            passes = 1,
            colormultiply = 1,
            red = 1,
            green = 1,
            blue = 1,
        },
        EquipSound = "",
        UnequipSound = "",
        -- Overlay = Material("arctic_nvg/shades.png"),
        ScaleToSquare = false,
        Entity = "arctic_nvg_shades_white",
        Offset = Vector(-0.5, 0, 0),
        OffsetAngle = Angle(0, 0, 0)
    },
    {
        ShortName = "shades_a",
        VManipIn = "nvg_aviators_in",
        VManipOut = "nvg_aviators_out",
        EquipDelay = 1.41,
        UnequipDelay = 0.25,
        NoBrightenWorld = true,
        Model = "models/arctic_nvgs/aviators.mdl",
        FullColor = false,
        NoFade = false,
        ColorCorrectSettings = {
            ["$pp_colour_addr"] = 0.03,
            ["$pp_colour_addg"] = 0.01,
            ["$pp_colour_addb"] = -0.1,
            ["$pp_colour_brightness"] = 0.01,
            ["$pp_colour_contrast"] = 4.5,
            ["$pp_colour_colour"] = 1,
            ["$pp_colour_mulr"] = 0,
            ["$pp_colour_mulg"] = 0,
            ["$pp_colour_mulb"] = 0,
        },
        BloomSettings = {
            darken = 0,
            multiply = 1,
            sizex = 4,
            sizey = 4,
            passes = 1,
            colormultiply = 1,
            red = 1,
            green = 1,
            blue = 1,
        },
        EquipSound = "",
        UnequipSound = "",
        -- Overlay = Material("arctic_nvg/shades.png"),
        ScaleToSquare = false,
        Entity = "arctic_nvg_shades_amber",
        Offset = Vector(-0.5, 0, 0),
        OffsetAngle = Angle(0, 0, 0)
    },
    {
        ShortName = "shades_b",
        VManipIn = "nvg_aviators_in",
        VManipOut = "nvg_aviators_out",
        EquipDelay = 1.41,
        UnequipDelay = 0.25,
        NoBrightenWorld = true,
        Model = "models/arctic_nvgs/aviators.mdl",
        FullColor = false,
        NoFade = false,
        ColorCorrectSettings = {
            ["$pp_colour_addr"] = -0.03,
            ["$pp_colour_addg"] = -0.03,
            ["$pp_colour_addb"] = 0.03,
            ["$pp_colour_brightness"] = 0.01,
            ["$pp_colour_contrast"] = 4.5,
            ["$pp_colour_colour"] = 1,
            ["$pp_colour_mulr"] = 0,
            ["$pp_colour_mulg"] = 0,
            ["$pp_colour_mulb"] = 0,
        },
        BloomSettings = {
            darken = 0,
            multiply = 1,
            sizex = 4,
            sizey = 4,
            passes = 1,
            colormultiply = 1,
            red = 1,
            green = 1,
            blue = 1,
        },
        EquipSound = "",
        UnequipSound = "",
        -- Overlay = Material("arctic_nvg/shades.png"),
        ScaleToSquare = false,
        Entity = "arctic_nvg_shades_blue",
        Offset = Vector(-0.5, 0, 0),
        OffsetAngle = Angle(0, 0, 0)
    },
    {
        ShortName = "shades_c",
        VManipIn = "nvg_aviators_in",
        VManipOut = "nvg_aviators_out",
        EquipDelay = 1.41,
        UnequipDelay = 0.25,
        NoBrightenWorld = true,
        Model = "models/arctic_nvgs/aviators.mdl",
        FullColor = false,
        NoFade = false,
        ColorCorrectSettings = {
            ["$pp_colour_addr"] = -0.05,
            ["$pp_colour_addg"] = 0,
            ["$pp_colour_addb"] = 0,
            ["$pp_colour_brightness"] = 0.01,
            ["$pp_colour_contrast"] = 4.5,
            ["$pp_colour_colour"] = 1,
            ["$pp_colour_mulr"] = 0,
            ["$pp_colour_mulg"] = 0,
            ["$pp_colour_mulb"] = 0,
        },
        BloomSettings = {
            darken = 0,
            multiply = 1,
            sizex = 4,
            sizey = 4,
            passes = 1,
            colormultiply = 1,
            red = 1,
            green = 1,
            blue = 1,
        },
        EquipSound = "",
        UnequipSound = "",
        -- Overlay = Material("arctic_nvg/shades.png"),
        ScaleToSquare = false,
        Entity = "arctic_nvg_shades_cyan",
        Offset = Vector(-0.5, 0, 0),
        OffsetAngle = Angle(0, 0, 0)
    },
    {
        ShortName = "shades_bw",
        VManipIn = "nvg_aviators_in",
        VManipOut = "nvg_aviators_out",
        EquipDelay = 1.41,
        UnequipDelay = 0.25,
        NoBrightenWorld = true,
        Model = "models/arctic_nvgs/aviators.mdl",
        FullColor = false,
        NoFade = false,
        ColorCorrectSettings = {
            ["$pp_colour_addr"] = 0,
            ["$pp_colour_addg"] = 0,
            ["$pp_colour_addb"] = 0,
            ["$pp_colour_brightness"] = 0.01,
            ["$pp_colour_contrast"] = 4.5,
            ["$pp_colour_colour"] = 1,
            ["$pp_colour_mulr"] = 0,
            ["$pp_colour_mulg"] = 0,
            ["$pp_colour_mulb"] = 0,
        },
        BloomSettings = {
            darken = 0,
            multiply = 1,
            sizex = 4,
            sizey = 4,
            passes = 1,
            colormultiply = 1,
            red = 1,
            green = 1,
            blue = 1,
        },
        EquipSound = "",
        UnequipSound = "",
        -- Overlay = Material("arctic_nvg/shades.png"),
        ScaleToSquare = false,
        Entity = "arctic_nvg_shades_grayscale",
        Offset = Vector(-0.5, 0, 0),
        OffsetAngle = Angle(0, 0, 0)
    },
    {
        ShortName = "shades_g",
        VManipIn = "nvg_aviators_in",
        VManipOut = "nvg_aviators_out",
        EquipDelay = 1.41,
        UnequipDelay = 0.25,
        NoBrightenWorld = true,
        Model = "models/arctic_nvgs/aviators.mdl",
        FullColor = false,
        NoFade = false,
        ColorCorrectSettings = {
            ["$pp_colour_addr"] = 0,
            ["$pp_colour_addg"] = 0.025,
            ["$pp_colour_addb"] = -0.05,
            ["$pp_colour_brightness"] = 0.01,
            ["$pp_colour_contrast"] = 4.5,
            ["$pp_colour_colour"] = 1,
            ["$pp_colour_mulr"] = 0,
            ["$pp_colour_mulg"] = 0,
            ["$pp_colour_mulb"] = 0,
        },
        BloomSettings = {
            darken = 0,
            multiply = 1,
            sizex = 4,
            sizey = 4,
            passes = 1,
            colormultiply = 1,
            red = 1,
            green = 1,
            blue = 1,
        },
        EquipSound = "",
        UnequipSound = "",
        -- Overlay = Material("arctic_nvg/shades.png"),
        ScaleToSquare = false,
        Entity = "arctic_nvg_shades_green",
        Offset = Vector(-0.5, 0, 0),
        OffsetAngle = Angle(0, 0, 0)
    },
    {
        ShortName = "shades_hp",
        VManipIn = "nvg_aviators_in",
        VManipOut = "nvg_aviators_out",
        EquipDelay = 1.41,
        UnequipDelay = 0.25,
        NoBrightenWorld = true,
        Model = "models/arctic_nvgs/aviators.mdl",
        FullColor = false,
        NoFade = false,
        ColorCorrectSettings = {
            ["$pp_colour_addr"] = 0.04,
            ["$pp_colour_addg"] = -0.05,
            ["$pp_colour_addb"] = 0.005,
            ["$pp_colour_brightness"] = 0.01,
            ["$pp_colour_contrast"] = 4.5,
            ["$pp_colour_colour"] = 1,
            ["$pp_colour_mulr"] = 0,
            ["$pp_colour_mulg"] = 0,
            ["$pp_colour_mulb"] = 0,
        },
        BloomSettings = {
            darken = 0,
            multiply = 1,
            sizex = 4,
            sizey = 4,
            passes = 1,
            colormultiply = 1,
            red = 1,
            green = 1,
            blue = 1,
        },
        EquipSound = "",
        UnequipSound = "",
        -- Overlay = Material("arctic_nvg/shades.png"),
        ScaleToSquare = false,
        Entity = "arctic_nvg_shades_hotpink",
        Offset = Vector(-0.5, 0, 0),
        OffsetAngle = Angle(0, 0, 0)
    },
    {
        ShortName = "shades_p",
        VManipIn = "nvg_aviators_in",
        VManipOut = "nvg_aviators_out",
        EquipDelay = 1.41,
        UnequipDelay = 0.25,
        NoBrightenWorld = true,
        Model = "models/arctic_nvgs/aviators.mdl",
        FullColor = false,
        NoFade = false,
        ColorCorrectSettings = {
            ["$pp_colour_addr"] = -0.01,
            ["$pp_colour_addg"] = -0.05,
            ["$pp_colour_addb"] = 0.02,
            ["$pp_colour_brightness"] = 0.01,
            ["$pp_colour_contrast"] = 4.5,
            ["$pp_colour_colour"] = 1,
            ["$pp_colour_mulr"] = 0,
            ["$pp_colour_mulg"] = 0,
            ["$pp_colour_mulb"] = 0,
        },
        BloomSettings = {
            darken = 0,
            multiply = 1,
            sizex = 4,
            sizey = 4,
            passes = 1,
            colormultiply = 1,
            red = 1,
            green = 1,
            blue = 1,
        },
        EquipSound = "",
        UnequipSound = "",
        -- Overlay = Material("arctic_nvg/shades.png"),
        ScaleToSquare = false,
        Entity = "arctic_nvg_shades_purple",
        Offset = Vector(-0.5, 0, 0),
        OffsetAngle = Angle(0, 0, 0)
    },
    {
        ShortName = "shades_r",
        VManipIn = "nvg_aviators_in",
        VManipOut = "nvg_aviators_out",
        EquipDelay = 1.41,
        UnequipDelay = 0.25,
        NoBrightenWorld = true,
        Model = "models/arctic_nvgs/aviators.mdl",
        FullColor = false,
        NoFade = false,
        ColorCorrectSettings = {
            ["$pp_colour_addr"] = 0.05,
            ["$pp_colour_addg"] = -0.05,
            ["$pp_colour_addb"] = -0.05,
            ["$pp_colour_brightness"] = 0.01,
            ["$pp_colour_contrast"] = 4.5,
            ["$pp_colour_colour"] = 1,
            ["$pp_colour_mulr"] = 0,
            ["$pp_colour_mulg"] = 0,
            ["$pp_colour_mulb"] = 0,
        },
        BloomSettings = {
            darken = 0,
            multiply = 1,
            sizex = 4,
            sizey = 4,
            passes = 1,
            colormultiply = 1,
            red = 1,
            green = 1,
            blue = 1,
        },
        EquipSound = "",
        UnequipSound = "",
        -- Overlay = Material("arctic_nvg/shades.png"),
        ScaleToSquare = false,
        Entity = "arctic_nvg_shades_red",
        Offset = Vector(-0.5, 0, 0),
        OffsetAngle = Angle(0, 0, 0)
    },
    {
        ShortName = "shades_ru",
        VManipIn = "nvg_aviators_in",
        VManipOut = "nvg_aviators_out",
        EquipDelay = 1.41,
        UnequipDelay = 0.25,
        NoBrightenWorld = true,
        Model = "models/arctic_nvgs/aviators.mdl",
        FullColor = false,
        NoFade = false,
        ColorCorrectSettings = {
            ["$pp_colour_addr"] = -0.05,
            ["$pp_colour_addg"] = 0.01,
            ["$pp_colour_addb"] = -0.1,
            ["$pp_colour_brightness"] = 0.01,
            ["$pp_colour_contrast"] = 4.5,
            ["$pp_colour_colour"] = 1,
            ["$pp_colour_mulr"] = 0,
            ["$pp_colour_mulg"] = 0,
            ["$pp_colour_mulb"] = 0,
        },
        BloomSettings = {
            darken = 0,
            multiply = 1,
            sizex = 4,
            sizey = 4,
            passes = 1,
            colormultiply = 1,
            red = 1,
            green = 1,
            blue = 1,
        },
        EquipSound = "",
        UnequipSound = "",
        -- Overlay = Material("arctic_nvg/shades.png"),
        ScaleToSquare = false,
        Entity = "arctic_nvg_shades_russian",
        Offset = Vector(-0.5, 0, 0),
        OffsetAngle = Angle(0, 0, 0)
    },
    {
        ShortName = "shades_teal",
        VManipIn = "nvg_aviators_in",
        VManipOut = "nvg_aviators_out",
        EquipDelay = 1.41,
        UnequipDelay = 0.25,
        NoBrightenWorld = true,
        Model = "models/arctic_nvgs/aviators.mdl",
        FullColor = false,
        NoFade = false,
        ColorCorrectSettings = {
            ["$pp_colour_addr"] = -0.04,
            ["$pp_colour_addg"] = 0.02,
            ["$pp_colour_addb"] = 0.01,
            ["$pp_colour_brightness"] = 0.01,
            ["$pp_colour_contrast"] = 4.5,
            ["$pp_colour_colour"] = 1,
            ["$pp_colour_mulr"] = 0,
            ["$pp_colour_mulg"] = 0,
            ["$pp_colour_mulb"] = 0,
        },
        BloomSettings = {
            darken = 0,
            multiply = 1,
            sizex = 4,
            sizey = 4,
            passes = 1,
            colormultiply = 1,
            red = 1,
            green = 1,
            blue = 1,
        },
        EquipSound = "",
        UnequipSound = "",
        -- Overlay = Material("arctic_nvg/shades.png"),
        ScaleToSquare = false,
        Entity = "arctic_nvg_shades_teal",
        Offset = Vector(-0.5, 0, 0),
        OffsetAngle = Angle(0, 0, 0)
    },
    {
        ShortName = "shades_t",
        VManipIn = "nvg_aviators_in",
        VManipOut = "nvg_aviators_out",
        EquipDelay = 1.41,
        UnequipDelay = 0.25,
        NoBrightenWorld = true,
        Model = "models/arctic_nvgs/aviators.mdl",
        FullColor = false,
        NoFade = false,
        ThermalVision = true,
        ThermalHighlight = Color(255, 0, 0),
        ColorCorrectSettings = {
            ["$pp_colour_addr"] = -0.1,
            ["$pp_colour_addg"] = -0.1,
            ["$pp_colour_addb"] = 0.1,
            ["$pp_colour_brightness"] = -0.1,
            ["$pp_colour_contrast"] = 1,
            ["$pp_colour_colour"] = 1,
            ["$pp_colour_mulr"] = 0,
            ["$pp_colour_mulg"] = 0,
            ["$pp_colour_mulb"] = 0,
        },
        EquipSound = "",
        UnequipSound = "",
        Overlay = Material("arctic_nvg/shades.png"),
        ScaleToSquare = false,
        Entity = "arctic_nvg_shades_thermal",
        Offset = Vector(-0.5, 0, 0),
        OffsetAngle = Angle(0, 0, 0)
    },
}

ArcticNVGs_ShortNameToID = {}

for i, k in pairs(ArcticNVGs) do
    ArcticNVGs_ShortNameToID[k.ShortName or ""] = i
end

CreateConVar("sh_arctic_nvg_losegoggles", "1", FCVAR_REPLICATED + FCVAR_ARCHIVE, "")

function ArcticNVGs_GetPlayerGoggles(ply)
    local goggles = ply:GetNWInt("nvg", 0)
    if goggles == 0 then return end

    return ArcticNVGs[goggles]
end